# Generated by Django 3.0.3 on 2020-02-22 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('icon_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PlantTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('days_after_plant', models.IntegerField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='growlog.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('project_pack', models.CharField(max_length=400)),
                ('smart', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_date', models.DateTimeField(auto_now_add=True)),
                ('harvest_date', models.DateTimeField()),
                ('harvested_date', models.DateTimeField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growlog.Plant')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='growlog.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPlantTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_date', models.DateTimeField()),
                ('done_date', models.DateTimeField(null=True)),
                ('project_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='growlog.ProjectPlant')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growlog.PlantTask')),
            ],
        ),
    ]
